
services:
  bui-client:
    container_name: bui-client
    env_file:
      - .env.dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - bui-network

networks:
  bui-network:
    name: bui-network
    driver: bridge
